const keys = [
  {
    keycode: 192,
    code: 'Backquote',
    charEng: '`',
    charRus: 'ё',
    extraEng: '~',
    extraRus: 'Ё',
  },
  {
    keycode: 49,
    code: 'Digit1',
    charRus: '1',
    charEng: '1',
    extraEng: '!',
    extraRus: '!',
  },
  {
    keycode: 50,
    code: 'Digit2',
    charRus: '2',
    charEng: '2',
    extraEng: '@',
    extraRus: '"',
  },
  {
    keycode: 51,
    code: 'Digit3',
    charRus: '3',
    charEng: '3',
    extraEng: '#',
    extraRus: '№',
  },
  {
    keycode: 52,
    code: 'Digit4',
    charRus: '4',
    charEng: '4',
    extraEng: '$',
    extraRus: ';',
  },
  {
    keycode: 53,
    code: 'Digit5',
    charRus: '5',
    charEng: '5',
    extraEng: '%',
    extraRus: '%',
  },
  {
    keycode: 54,
    code: 'Digit6',
    charRus: '6',
    charEng: '6',
    extraEng: '^',
    extraRus: ':',
  },
  {
    keycode: 55,
    code: 'Digit7',
    charRus: '7',
    charEng: '7',
    extraEng: '&',
    extraRus: '?',
  },
  {
    keycode: 56,
    code: 'Digit8',
    charRus: '8',
    charEng: '8',
    extraEng: '*',
    extraRus: '*',
  },
  {
    keycode: 57,
    code: 'Digit9',
    charRus: '9',
    charEng: '9',
    extraEng: '(',
    extraRus: '(',
  },
  {
    keycode: 48,
    code: 'Digit0',
    charRus: '0',
    charEng: '0',
    extraEng: ')',
    extraRus: ')',
  },
  {
    keycode: 109,
    code: 'Minus',
    charRus: '-',
    charEng: '-',
    extraEng: '_',
    extraRus: '_',
  },
  {
    keycode: 61,
    code: 'Equal',
    charRus: '=',
    charEng: '=',
    extraEng: '+',
    extraRus: '+',
  },
  {
    keycode: 81,
    code: 'Backspace',
    width: 'key__size20',
    charRus: 'Backspace',
    charEng: 'Backspace',
    special: true,
  },
  {
    keycode: 9,
    code: 'Tab',
    charRus: 'Tab',
    charEng: 'Tab',
    special: true,
  },
  {
    keycode: 81,
    code: 'KeyQ',
    charRus: 'й',
    charEng: 'q',
  },
  {
    keycode: 87,
    code: 'KeyW',
    charRus: 'ц',
    charEng: 'w',
  },
  {
    keycode: 69,
    code: 'KeyE',
    charRus: 'у',
    charEng: 'e',
  },
  {
    keycode: 82,
    code: 'KeyR',
    charRus: 'к',
    charEng: 'r',
  },
  {
    keycode: 84,
    code: 'KeyT',
    charRus: 'е',
    charEng: 't',
  },
  {
    keycode: 89,
    code: 'KeyY',
    charRus: 'н',
    charEng: 'y',
  },
  {
    keycode: 85,
    code: 'KeyU',
    charRus: 'г',
    charEng: 'u',
  },
  {
    keycode: 73,
    code: 'KeyI',
    charRus: 'ш',
    charEng: 'i',
  },
  {
    keycode: 79,
    code: 'KeyO',
    charRus: 'щ',
    charEng: 'o',
  },
  {
    keycode: 80,
    code: 'KeyP',
    charRus: 'з',
    charEng: 'p',
  },
  {
    keycode: 219,
    code: 'BracketLeft',
    charRus: 'х',
    charEng: '[',
    extraEng: '{',
    extraRus: 'Х',
  },
  {
    keycode: 221,
    code: 'BracketRight',
    charRus: 'ъ',
    charEng: ']',
    extraEng: '}',
    extraRus: 'Ъ',
  },
  {
    keycode: 220,
    code: 'Backslash',
    charRus: '\\',
    charEng: '\\',
    extraEng: '|',
    extraRus: '|',
  },
  {
    keycode: 46,
    code: 'Delete',
    charRus: 'Del',
    charEng: 'Del',
    special: true,
  },
  {
    width: 'key__size15',
    keycode: 20,
    code: 'CapsLock',
    charRus: 'CapsLock',
    charEng: 'CapsLock',
    special: true,
  },
  {
    keycode: 65,
    code: 'KeyA',
    charRus: 'ф',
    charEng: 'a',
  },
  {
    keycode: 83,
    code: 'KeyS',
    charRus: 'ы',
    charEng: 's',
  },
  {
    keycode: 68,
    code: 'KeyD',
    charRus: 'в',
    charEng: 'd',
  },
  {
    keycode: 70,
    code: 'KeyF',
    charRus: 'а',
    charEng: 'f',
  },
  {
    keycode: 71,
    code: 'KeyG',
    charRus: 'п',
    charEng: 'g',
  },
  {
    keycode: 72,
    code: 'KeyH',
    charRus: 'р',
    charEng: 'h',
  },
  {
    keycode: 74,
    code: 'KeyJ',
    charRus: 'о',
    charEng: 'j',
  },
  {
    keycode: 75,
    code: 'KeyK',
    charRus: 'л',
    charEng: 'k',
  },
  {
    keycode: 76,
    code: 'KeyL',
    charRus: 'д',
    charEng: 'l',
  },
  {
    keycode: 186,
    code: 'Semicolon',
    charRus: 'ж',
    charEng: ';',
    extraEng: ':',
    extraRus: 'Ж',
  },
  {
    keycode: 222,
    code: 'Quote',
    charRus: 'э',
    charEng: '\'',
    extraEng: '"',
    extraRus: 'Э',
  },
  {
    width: 'key__size25',
    keycode: 13,
    code: 'Enter',
    charRus: 'Enter',
    charEng: 'Enter',
    special: true,
  },
  {
    width: 'key__size20',
    keycode: 16,
    code: 'ShiftLeft',
    charRus: 'Shift',
    charEng: 'Shift',
    special: true,
  },
  {
    keycode: 90,
    code: 'KeyZ',
    charRus: 'я',
    charEng: 'z',
  },
  {
    keycode: 88,
    code: 'KeyX',
    charRus: 'ч',
    charEng: 'x',
  },
  {
    keycode: 67,
    code: 'KeyC',
    charRus: 'с',
    charEng: 'c',
  },
  {
    keycode: 86,
    code: 'KeyV',
    charRus: 'м',
    charEng: 'v',
  },
  {
    keycode: 66,
    code: 'KeyB',
    charRus: 'и',
    charEng: 'b',
  },
  {
    keycode: 78,
    code: 'KeyN',
    charRus: 'т',
    charEng: 'n',
  },
  {
    keycode: 77,
    code: 'KeyM',
    charRus: 'ь',
    charEng: 'm',
  },
  {
    keycode: 188,
    code: 'Comma',
    charRus: 'б',
    charEng: ',',
    extraEng: '<',
    extraRus: 'Б',

  },
  {
    keycode: 190,
    code: 'Period',
    charRus: 'ю',
    charEng: '.',
    extraEng: '>',
    extraRus: 'Ю',

  },
  {
    keycode: 191,
    code: 'Slash',
    charRus: '.',
    charEng: '/',
    extraEng: '?',
    extraRus: ',',
  },
  {
    keycode: 38,
    code: 'ArrowUp',
    charRus: '&#8593;',
    charEng: '&#8593;',
    special: true,
  },
  {
    width: 'key__size20',
    keycode: 16,
    code: 'ShiftRight',
    charRus: 'Shift',
    charEng: 'Shift',
    special: true,
  },
  {
    width: 'key__size15',
    keycode: 17,
    code: 'ControlLeft',
    charRus: 'Ctrl',
    charEng: 'Ctrl',
    special: true,
  },
  {
    keycode: 91,
    code: 'MetaLeft',
    charRus: 'Win',
    charEng: 'Win',
    special: true,
  },
  {
    keycode: 18,
    code: 'AltLeft',
    charRus: 'Alt',
    charEng: 'Alt',
    special: true,
  },
  {
    width: 'key__size70',
    keycode: 32,
    code: 'Space',
    charRus: 'Space',
    charEng: 'Space',
    special: true,
  },
  {
    keycode: 18,
    code: 'AltRight',
    charRus: 'Alt',
    charEng: 'Alt',
    special: true,
  },
  {
    width: 'key__size15',
    keycode: 17,
    code: 'ControlRight',
    charRus: 'Ctrl',
    charEng: 'Ctrl',
    special: true,
  },
  {
    keycode: 37,
    code: 'ArrowLeft',
    charRus: '&#8592;',
    charEng: '&#8592;',
    special: true,
  },
  {
    keycode: 40,
    code: 'ArrowDown',
    charRus: '&#8595;',
    charEng: '&#8595;',
    special: true,
  },
  {
    keycode: 39,
    code: 'ArrowRight',
    charRus: '&#8594;',
    charEng: '&#8594;',
    special: true,
  },

];

export default keys;
